version: '3.7'
services:
  resume:
    build:
      context: .
      dockerfile: Dockerfile
    image: dashboard
    container_name: dashboard
    restart: always
    ports:
      - 8080:8080
    networks:
      - nginx

networks:
  nginx:
    external: true
